# Metadata
baseURL = "https://ut-eclair.github.io"
languageCode = "en-us"
title = "UT Engineering and Computational Learning of Artifical Intelligence and Robotics"
theme = "navigator-hugo"
summaryLength = 10

publishDir = "docs" # Tells hugo where to put the built site
pygmentsCodeFences = true # Allows code block syntax highlighting for markdown


# Site Variables
[params]
logo = "images/logos/small_eclair_logo.png" # Logo in top left corner

# Site Meta Data
title = "UT ECLAIR" # Site Title
author = "Conrad Li" # Site Creator
description = "The University of Texas at Austin's Engineering and Computational Learning in Artificial Intelligence and Robotics"
languageCode = "en-us" # Language
dateFormat = "January 2, 2006" # How to format dates
home = "Home" # Name of navigation item that targets the homepage
menufixed = false

# Footer Social Media Variables
socialMediaTitle = "Follow Us"
githubLink = "https://github.com/UT-ECLAIR" # Github Link
githubIcon = "images/social_icons/GitHub-Mark-Light-32px.png" # Github Icon
# Footer Email Variables
emailTitle = "Contact Us"
emailAddress = "uteclair@gmail.com"
# Footer Discord Variables
discordTitle = "Join Us"
discordLink = "https://discord.gg/aPSsBzh9" # Discord Invite link
discordIcon = "images/social_icons/Discord-Logo-White.png" # Discord Icon

# Cookies
[params.cookies]
enable = false
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Our mission is to drive innovation in AI and robotics at the undergraduate level."
description = ""
button  = true
btnText = "View Our Current Projects"
btnURL  = "projects"
eclairLogo = "images/logos/ECLAIR_logo2.png"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Geared toward helping students pursue their passion for robotics"
description = "The Engineering and Computational Learning of Artificial Intelligence in Robotics (ECLAIR) is a club at UT Austin dedicated to helping all robot-loving students to transform their passionate robotics ideas into reality. We provide the robotics parts and teach members state-of-the-art machine learning techiniques such as neural networks and reinforcement learning to give students the ability to pursue their robotics projects. If you have a cool robot you want to build, come join us!"

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = false
#topTitle= "DROP US A NOTE"
#title   = "Contact Us."
#subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
#address = "14/05, Stockhome <br> Victori Palace , United States"
#phone   = "(03) 9283 2617"
#fax     = "+61 3827 3590"
#facebook= "https://www.facebook.com/"
#twitter = "https://twitter.com/"
#linkedin= "https://www.linkedin.com/"
#instagram= "https://www.instagram.com/"

# Site Menus
[menu]

# Navbar Menus
[[menu.nav]]
name    = "Projects"
url     = "projects"
weight  = 2

[[menu.nav]]
name    = "Members"
url     = "members"
weight  = 3


[[menu.nav]]
name    = "Sponsors"
url     = "sponsors"
weight  = 4

# TODO: Maybe do more extensive about us page later?
#[[menu.nav]]
#name    = "About" # Name of navigation item
#url     = "about" # URL suffix leading to the target page (all webpage names can be vie)
#weight  = 2 # The ordering of the navigation item  (lower means earlier ordering)

# TODO: Maybe do
#[[menu.nav]]
#name    = "Blog"
#url     = "blog"
#weight  = 5